"""
Image Relevance Checker — verifies if retrieved images are relevant to the user's query.

Uses embeddings to calculate cosine similarity between the user's query
and the image description (generated by llama-4-scout during ingestion).
If the similarity is above the threshold (0.75), the image is kept.
"""

import logging
import numpy as np
from typing import Optional

from retrieval.embedding import get_embedding_model
from schemas.citation import Citation
from langfuse.decorators import observe

logger = logging.getLogger(__name__)

# Threshold for semantic relevance
COSINE_THRESHOLD = 0.75


def cosine_similarity(vec1: list[float], vec2: list[float]) -> float:
    """Calculate cosine similarity between two vectors."""
    v1 = np.array(vec1)
    v2 = np.array(vec2)
    norm1 = np.linalg.norm(v1)
    norm2 = np.linalg.norm(v2)
    
    if norm1 == 0 or norm2 == 0:
        return 0.0
        
    return float(np.dot(v1, v2) / (norm1 * norm2))


@observe()
def check_image_relevance(
    query: str,
    citation: Citation,
    query_embedding: Optional[list[float]] = None
) -> bool:
    """Check if the image in the citation is relevant to the user's query.
    
    Args:
        query: User's chat query.
        citation: The Citation object containing the image description.
        query_embedding: Pre-computed embedding for the query (optional).
        
    Returns:
        bool: True if image is highly relevant, False otherwise.
    """
    if not citation.has_image or not citation.image_description:
        return False
        
    try:
        model = get_embedding_model()
        
        # Embed query if not provided
        if query_embedding is None:
            query_embedding = model.embed_query(query)
            
        # Embed image description
        desc_embedding = model.embed_query(citation.image_description)
        
        # Calculate similarity
        similarity = cosine_similarity(query_embedding, desc_embedding)
        
        is_relevant = similarity > COSINE_THRESHOLD
        
        logger.info(
            "Image relevance check: similarity=%.2f, threshold=%.2f, relevant=%s",
            similarity, COSINE_THRESHOLD, is_relevant
        )
        
        return is_relevant

    except Exception as exc:
        logger.warning("Failed to calculate image relevance: %s — defaulting to True", exc)
        return True
