"""
Citation schema for robust source attribution with image support.
"""

from typing import Optional
from pydantic import BaseModel, Field


class Citation(BaseModel):
    """A rich citation linking an answer back to its source chunk and media."""
    
    # Core fields (already exist — do not remove)
    text: str = Field(..., description="Verbatim excerpt from chunk (max 200 chars, NOT paraphrased)")
    source_document: str = Field(..., description="e.g. 'AAPL_10K_2023'")
    page_number: int = Field(default=0, description="Page number of the original document")
    section: str = Field(default="General", description="e.g. 'Risk Factors', 'MD&A'")
    chunk_id: str = Field(..., description="Real Qdrant point ID — never fake")

    # New fields
    confidence: float = Field(default=0.0, description="Qdrant retrieval score (0.0–1.0)")
    chunk_preview: str = Field(default="", description="First 150 chars of chunk for display")

    # Image fields
    has_image: bool = Field(default=False, description="Whether this chunk has an associated image")
    image_url: Optional[str] = Field(default=None, description="URL (Jina) or local path (PDF)")
    image_description: Optional[str] = Field(default=None, description="Generated by llama-4-scout")
    image_type: Optional[str] = Field(default=None, description="'table' | 'chart' | 'graph' | 'diagram' | 'other'")

    # Retrieval scores — dense_score is cosine similarity (0-1), more useful for display
    dense_score: float = Field(default=0.0, description="Cosine similarity from dense vector search (0-1)")

    def format_for_display(self) -> str:
        """Format the citation for UI rendering."""
        return (
            f"Source: {self.source_document} | Page {self.page_number} | Section: {self.section}\n"
            f"Chunk preview: \"{self.chunk_preview}...\"\n"
            f"Relevance: {self.confidence:.0%}"
        )
